-- Primera practica
CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);

-- ACTIVAMOS MODO DE CONSOLA
SET SERVEROUTPUT ON;

--BLOQUE PL SQL
DECLARE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
YEARS:=42;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('tU EDAD EN DIAS ES:'||EDAD);
END;
-- Primera practica
CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);

-- ACTIVAMOS MODO DE CONSOLA
SET SERVEROUTPUT ON;

--BLOQUE PL SQL
DECLARE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
YEARS:=42;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('tU EDAD EN DIAS ES:'||EDAD);
END;
/
--PRACTICA CLASE 2
--CREAR UN BLOQUE PL SQUL QUE GENERE ,REGISTROS EN SECUENCIA ASCENDENTE DE LA TABLA DANCE
BEGIN
FOR I IN 1..200000 LOOP
INSERT INTO DANCE VALUES(1,'CAMPOS',44);
END LOOP;
END;
/

--HACEMOS UN SELECT
SELECT * FROM DANCE;

--SISTEMITA DE PELICULAS LA DE SALA SERA DE TAREA

CREATE TABLE PELICULA (ID_PELICULA INTERGER,
                      TITULO VARCHAR2(120),
                      SINOPSIS VARCHAR2(500),
                      CLASIFICACIÓN VARCHAR2(5),
                      CONSTRAINT FK_ID_PELICULA PRIMARY KEY ( ID_PELICULA)
                      );
                      DESCRIBE PELICULA;
                      
CREATE TABLE HORARIOS (ID_HORARIO INTERGER,
                      HORARIO VARCHAR2(0),
                      CONSTRAINT FK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
                      CONSTRAINT FK1_ID_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
                      );
              
